/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#f0f9ff',
          100: '#e0f2fe',
          200: '#bae6fd',
          300: '#7dd3fc',
          400: '#38bdf8',
          500: '#0ea5e9',
          600: '#0284c7',
          700: '#0369a1',
          800: '#075985',
          900: '#0c4a6e',
        },
        secondary: {
          50: '#f8fafc',
          100: '#f1f5f9',
          200: '#e2e8f0',
          300: '#cbd5e1',
          400: '#94a3b8',
          500: '#64748b',
          600: '#475569',
          700: '#334155',
          800: '#1e293b',
          900: '#0f172a',
        },
        border: '#e2e8f0',
        background: '#ffffff',
        foreground: '#0f172a',
        ring: '#0ea5e9',
        // NANI TECH Theme Colors
        card: '#1C1F27',
        'card-foreground': '#EAEAEA',
        popover: '#1C1F27',
        'popover-foreground': '#EAEAEA',
        muted: '#1C1F27',
        'muted-foreground': '#EAEAEA80',
        accent: '#E53935',
        'accent-foreground': '#EAEAEA',
        destructive: '#E53935',
        input: '#0C0F1680',
        'chart-1': '#00E5FF',
        'chart-2': '#E53935',
        'chart-3': '#0066CC',
        'chart-4': '#FF6B6B',
        'chart-5': '#14273D',
        sidebar: '#1C1F27',
        'sidebar-foreground': '#EAEAEA',
        'sidebar-primary': '#00E5FF',
        'sidebar-primary-foreground': '#0C0F16',
        'sidebar-accent': '#E53935',
        'sidebar-accent-foreground': '#EAEAEA',
        'sidebar-border': '#00E5FF33',
        'sidebar-ring': '#00E5FF'
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'slide-up': 'slideUp 0.5s ease-out',
        'slide-down': 'slideDown 0.5s ease-out',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
}
