name: Track PR and Issues

on:
  workflow_dispatch:
  pull_request:
    types: [opened, closed, merged]
  issues:
    types: [opened, closed]

jobs:
  track_pr:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Generate GitHub token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PEM }}
          
      - name: Use GitHub API
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          # Get repository information
          gh api repos/${{ github.repository }} --jq '.name, .full_name, .description'
          
          # Track PR information
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "PR Number: ${{ github.event.number }}"
            echo "PR Title: ${{ github.event.pull_request.title }}"
            echo "PR State: ${{ github.event.pull_request.state }}"
            echo "PR Author: ${{ github.event.pull_request.user.login }}"
            
            # Get PR details using the generated token
            gh api repos/${{ github.repository }}/pulls/${{ github.event.number }} \
              --jq '.title, .body, .head.ref, .base.ref, .mergeable'
          fi
          
          # Track issue information
          if [ "${{ github.event_name }}" = "issues" ]; then
            echo "Issue Number: ${{ github.event.issue.number }}"
            echo "Issue Title: ${{ github.event.issue.title }}"
            echo "Issue State: ${{ github.event.issue.state }}"
            echo "Issue Author: ${{ github.event.issue.user.login }}"
            
            # Get issue details using the generated token
            gh api repos/${{ github.repository }}/issues/${{ github.event.issue.number }} \
              --jq '.title, .body, .labels[].name, .assignees[].login'
          fi
          
      - name: Log token expiration
        run: |
          echo "Generated token expires in 60 minutes"
          echo "Token created at: $(date)"
          echo "Token expires at: $(date -d '+60 minutes')"
