name: Track PR and Issues (Simple)

on:
  workflow_dispatch:
  pull_request:
    types: [opened, closed, merged]
  issues:
    types: [opened, closed]

jobs:
  track_pr:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Use GitHub API with GITHUB_TOKEN
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get repository information
          gh api repos/${{ github.repository }} --jq '.name, .full_name, .description'
          
          # Track PR information
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "PR Number: ${{ github.event.number }}"
            echo "PR Title: ${{ github.event.pull_request.title }}"
            echo "PR State: ${{ github.event.pull_request.state }}"
            echo "PR Author: ${{ github.event.pull_request.user.login }}"
            
            # Get PR details using GITHUB_TOKEN
            gh api repos/${{ github.repository }}/pulls/${{ github.event.number }} \
              --jq '.title, .body, .head.ref, .base.ref, .mergeable'
          fi
          
          # Track issue information
          if [ "${{ github.event_name }}" = "issues" ]; then
            echo "Issue Number: ${{ github.event.issue.number }}"
            echo "Issue Title: ${{ github.event.issue.title }}"
            echo "Issue State: ${{ github.event.issue.state }}"
            echo "Issue Author: ${{ github.event.issue.user.login }}"
            
            # Get issue details using GITHUB_TOKEN
            gh api repos/${{ github.repository }}/issues/${{ github.event.issue.number }} \
              --jq '.title, .body, .labels[].name, .assignees[].login'
          fi
          
      - name: Log workflow information
        run: |
          echo "Workflow triggered by: ${{ github.event_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"
          echo "Commit: ${{ github.sha }}"
          echo "Actor: ${{ github.actor }}"
